# Generated by Django 3.2.6 on 2022-01-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
